// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function AirplayVideoIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M5 3C3.34315 3 2 4.34315 2 6V14.05C2 15.6792 3.32076 17 4.95 17H5C5.55228 17 6 16.5523 6 16C6 15.4477 5.55228 15 5 15H4.95C4.42533 15 4 14.5747 4 14.05V6C4 5.44772 4.44772 5 5 5H19C19.5523 5 20 5.44772 20 6V14C20 14.5523 19.5523 15 19 15C18.4477 15 18 15.4477 18 16C18 16.5523 18.4477 17 19 17C20.6569 17 22 15.6569 22 14V6C22 4.34315 20.6569 3 19 3H5ZM10.2517 13.0879C11.0137 11.7162 12.9863 11.7162 13.7483 13.0879L17.0488 19.0287C17.7894 20.3618 16.8255 22 15.3005 22H8.69951C7.17454 22 6.21061 20.3618 6.9512 19.0287L10.2517 13.0879Z" />
    </Icon>
  );
}
