// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function AlignLayoutTopIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M22.5 4C22.5 4.55229 22.0523 5 21.5 5L2.5 5C1.94772 5 1.5 4.55228 1.5 4C1.5 3.44772 1.94772 3 2.5 3H21.5C22.0523 3 22.5 3.44772 22.5 4ZM11 9.2C11 7.98497 10.015 7 8.8 7H6.2C4.98497 7 4 7.98497 4 9.2L4 18.8C4 20.015 4.98497 21 6.2 21H8.8C10.015 21 11 20.015 11 18.8L11 9.2ZM20 9.2C20 7.98497 19.015 7 17.8 7H15.2C13.985 7 13 7.98497 13 9.2V15.8C13 17.015 13.985 18 15.2 18H17.8C19.015 18 20 17.015 20 15.8V9.2Z" />
    </Icon>
  );
}
