// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function AlignLayoutCenterVerticallyJustifiedIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M9.5 18.8C9.5 20.015 8.51503 21 7.3 21H4.7C3.48497 21 2.5 20.015 2.5 18.8V12V5.2C2.5 3.98497 3.48497 3 4.7 3H7.3C8.51503 3 9.5 3.98497 9.5 5.2V11L14.5 11V8.7C14.5 7.48497 15.485 6.5 16.7 6.5L19.3 6.5C20.515 6.5 21.5 7.48497 21.5 8.7V12V15.3C21.5 16.515 20.515 17.5 19.3 17.5H16.7C15.485 17.5 14.5 16.515 14.5 15.3V13L9.5 13V18.8Z" />
    </Icon>
  );
}
