// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function AlignLayoutRightIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M19 2.5C19 1.94772 19.4477 1.5 20 1.5C20.5523 1.5 21 1.94772 21 2.5V21.5C21 22.0523 20.5523 22.5 20 22.5C19.4477 22.5 19 22.0523 19 21.5V2.5ZM17 6.2C17 4.98497 16.015 4 14.8 4H8.2C6.98497 4 6 4.98497 6 6.2V8.8C6 10.015 6.98497 11 8.2 11H14.8C16.015 11 17 10.015 17 8.8V6.2ZM17 15.2C17 13.985 16.015 13 14.8 13H5.2C3.98497 13 3 13.985 3 15.2V17.8C3 19.015 3.98497 20 5.2 20H14.8C16.015 20 17 19.015 17 17.8V15.2Z" />
    </Icon>
  );
}
