// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function ArrowUUpRightIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M14.2929 3.29289C13.9024 3.68342 13.9024 4.31658 14.2929 4.70711L17.5858 8H9.5C5.91015 8 3 10.9101 3 14.5C3 18.0899 5.91015 21 9.5 21H13C13.5523 21 14 20.5523 14 20C14 19.4477 13.5523 19 13 19H9.5C7.01472 19 5 16.9853 5 14.5C5 12.0147 7.01472 10 9.5 10H17.5858L14.2929 13.2929C13.9024 13.6834 13.9024 14.3166 14.2929 14.7071C14.6834 15.0976 15.3166 15.0976 15.7071 14.7071L20.7071 9.70711C21.0976 9.31658 21.0976 8.68342 20.7071 8.29289L15.7071 3.29289C15.3166 2.90237 14.6834 2.90237 14.2929 3.29289Z" />
    </Icon>
  );
}
