// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function ArrowTurnLeftUpIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M2.79289 10.7071C2.40237 10.3166 2.40237 9.68342 2.79289 9.29289L8.79289 3.29289C9.18342 2.90237 9.81658 2.90237 10.2071 3.29289L16.2071 9.29289C16.5976 9.68342 16.5976 10.3166 16.2071 10.7071C15.8166 11.0976 15.1834 11.0976 14.7929 10.7071L10.5 6.41421L10.5 16C10.5 16.5523 10.9477 17 11.5 17L20.5 17C21.0523 17 21.5 17.4477 21.5 18C21.5 18.5523 21.0523 19 20.5 19L11.5 19C9.84315 19 8.5 17.6569 8.5 16L8.5 6.41421L4.20711 10.7071C3.81658 11.0976 3.18342 11.0976 2.79289 10.7071Z" />
    </Icon>
  );
}
