// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function ArrowDropdownLeftIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M15.5 8.00001C15.5 7.6156 15.2797 7.26523 14.9332 7.09871C14.5867 6.93219 14.1755 6.979 13.8753 7.21914L8.87531 11.2191C8.63809 11.4089 8.5 11.6962 8.5 12C8.5 12.3038 8.63809 12.5911 8.87531 12.7809L13.8753 16.7809C14.1755 17.021 14.5867 17.0678 14.9332 16.9013C15.2797 16.7348 15.5 16.3844 15.5 16V8.00001Z" />
    </Icon>
  );
}
