// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function ArrowDropdownUpIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M16 15.5C16.3844 15.5 16.7348 15.2797 16.9013 14.9332C17.0678 14.5867 17.021 14.1755 16.7809 13.8753L12.7809 8.8753C12.5911 8.63809 12.3038 8.5 12 8.5C11.6962 8.5 11.4089 8.63809 11.2191 8.8753L7.21914 13.8753C6.979 14.1755 6.93219 14.5867 7.09871 14.9332C7.26523 15.2797 7.6156 15.5 8.00001 15.5L16 15.5Z" />
    </Icon>
  );
}
