// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function ArrowDropdownRightIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M8.5 16C8.5 16.3844 8.72035 16.7348 9.06681 16.9013C9.41328 17.0678 9.82453 17.021 10.1247 16.7809L15.1247 12.7809C15.3619 12.5911 15.5 12.3038 15.5 12C15.5 11.6962 15.3619 11.4089 15.1247 11.2191L10.1247 7.21914C9.82452 6.979 9.41328 6.93219 9.06681 7.09871C8.72035 7.26523 8.5 7.6156 8.5 8.00001V16Z" />
    </Icon>
  );
}
