// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function ArrowBlockUpRightIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M6.92663 7.34099C5.50921 5.92357 6.51308 3.5 8.51762 3.5H18.4998C19.6044 3.5 20.4998 4.39543 20.4998 5.5L20.4998 15.4822C20.4998 17.4868 18.0763 18.4907 16.6589 17.0732L15.7498 16.1642L11.4141 20.5C10.633 21.281 9.36668 21.281 8.58564 20.5L3.49985 15.4142C2.7188 14.6332 2.7188 13.3668 3.49985 12.5858L7.83564 8.25L6.92663 7.34099Z" />
    </Icon>
  );
}
