// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function ArrowFromLineDownIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M21 5C21.5523 5 22 4.55228 22 4C22 3.44772 21.5523 3 21 3H3C2.44772 3 2 3.44772 2 4C2 4.55229 2.44772 5 3 5L21 5ZM18.7071 15.7071C19.0976 15.3166 19.0976 14.6834 18.7071 14.2929C18.3166 13.9024 17.6834 13.9024 17.2929 14.2929L13 18.5858V9C13 8.44771 12.5523 8 12 8C11.4477 8 11 8.44771 11 9V18.5858L6.70711 14.2929C6.31658 13.9024 5.68342 13.9024 5.29289 14.2929C4.90237 14.6834 4.90237 15.3166 5.29289 15.7071L11.2929 21.7071C11.6834 22.0976 12.3166 22.0976 12.7071 21.7071L18.7071 15.7071Z" />
    </Icon>
  );
}
