// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function ArrowTurnUpRightIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M13.2929 2.79289C13.6834 2.40237 14.3166 2.40237 14.7071 2.79289L20.7071 8.79289C21.0976 9.18342 21.0976 9.81658 20.7071 10.2071L14.7071 16.2071C14.3166 16.5976 13.6834 16.5976 13.2929 16.2071C12.9024 15.8166 12.9024 15.1834 13.2929 14.7929L17.5858 10.5H8C7.44772 10.5 7 10.9477 7 11.5V20.5C7 21.0523 6.55228 21.5 6 21.5C5.44772 21.5 5 21.0523 5 20.5V11.5C5 9.84315 6.34315 8.5 8 8.5H17.5858L13.2929 4.20711C12.9024 3.81658 12.9024 3.18342 13.2929 2.79289Z" />
    </Icon>
  );
}
