// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function ArrowTurnLeftDownIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M2.79289 13.2929C2.40237 13.6834 2.40237 14.3166 2.79289 14.7071L8.79289 20.7071C9.18342 21.0976 9.81658 21.0976 10.2071 20.7071L16.2071 14.7071C16.5976 14.3166 16.5976 13.6834 16.2071 13.2929C15.8166 12.9024 15.1834 12.9024 14.7929 13.2929L10.5 17.5858L10.5 8C10.5 7.44772 10.9477 7 11.5 7L20.5 7C21.0523 7 21.5 6.55229 21.5 6C21.5 5.44772 21.0523 5 20.5 5L11.5 5C9.84315 5 8.5 6.34315 8.5 8L8.5 17.5858L4.20711 13.2929C3.81658 12.9024 3.18342 12.9024 2.79289 13.2929Z" />
    </Icon>
  );
}
