// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function ArrowULeftDownIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M3.29289 14.2929C3.68342 13.9024 4.31658 13.9024 4.70711 14.2929L8 17.5858L8 9.5C8 5.91015 10.9101 3 14.5 3C18.0898 3 21 5.91015 21 9.5L21 13C21 13.5523 20.5523 14 20 14C19.4477 14 19 13.5523 19 13L19 9.5C19 7.01472 16.9853 5 14.5 5C12.0147 5 10 7.01472 10 9.5L10 17.5858L13.2929 14.2929C13.6834 13.9024 14.3166 13.9024 14.7071 14.2929C15.0976 14.6834 15.0976 15.3166 14.7071 15.7071L9.70711 20.7071C9.31658 21.0976 8.68342 21.0976 8.29289 20.7071L3.29289 15.7071C2.90237 15.3166 2.90237 14.6834 3.29289 14.2929Z" />
    </Icon>
  );
}
