// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function ArrowToLineUpIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M21 5C21.5523 5 22 4.55228 22 4C22 3.44772 21.5523 3 21 3H3C2.44772 3 2 3.44772 2 4C2 4.55229 2.44772 5 3 5L21 5ZM18.7071 13.2929C19.0976 13.6834 19.0976 14.3166 18.7071 14.7071C18.3166 15.0976 17.6834 15.0976 17.2929 14.7071L13 10.4142V21C13 21.5523 12.5523 22 12 22C11.4477 22 11 21.5523 11 21V10.4142L6.70711 14.7071C6.31658 15.0976 5.68342 15.0976 5.29289 14.7071C4.90237 14.3166 4.90237 13.6834 5.29289 13.2929L11.2929 7.29289C11.6834 6.90237 12.3166 6.90237 12.7071 7.29289L18.7071 13.2929Z" />
    </Icon>
  );
}
