// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function ArrowBlockUpIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M13.4146 2.49985C12.6336 1.7188 11.3673 1.7188 10.5862 2.49985L3.42719 9.65886C2.00977 11.0763 3.01365 13.4998 5.01818 13.4998H7.00005V19.9998C7.00005 21.1044 7.89548 21.9998 9.00005 21.9998H15.0001C16.1046 21.9998 17.0001 21.1044 17.0001 19.9998V13.4998H18.9827C20.9872 13.4998 21.9911 11.0763 20.5736 9.65886L13.4146 2.49985Z" />
    </Icon>
  );
}
