// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function ArrowBlockDownLeftIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M15.4183 3.49985C14.6372 2.7188 13.3709 2.7188 12.5898 3.49985L8.25406 7.83564L7.34505 6.92663C5.92763 5.50921 3.50406 6.51308 3.50406 8.51762V18.4998C3.50406 19.6044 4.39949 20.4998 5.50406 20.4998L15.4863 20.4998C17.4908 20.4998 18.4947 18.0763 17.0773 16.6589L16.1683 15.7498L20.5041 11.4141C21.2851 10.633 21.2851 9.36668 20.5041 8.58564L15.4183 3.49985Z" />
    </Icon>
  );
}
