// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function ArrowBlockDownRightIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M8.58173 3.49985C9.36278 2.7188 10.6291 2.7188 11.4102 3.49985L15.7459 7.83564L16.655 6.92663C18.0724 5.50921 20.4959 6.51308 20.4959 8.51762V18.4998C20.4959 19.6044 19.6005 20.4998 18.4959 20.4998L8.51371 20.4998C6.50918 20.4998 5.50529 18.0763 6.92272 16.6589L7.83173 15.7498L3.49594 11.4141C2.71489 10.633 2.71489 9.36668 3.49594 8.58564L8.58173 3.49985Z" />
    </Icon>
  );
}
