// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function ArrowDropdownDownIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M8.00001 8.5C7.6156 8.5 7.26523 8.72035 7.09871 9.06681C6.93219 9.41328 6.979 9.82453 7.21914 10.1247L11.2191 15.1247C11.4089 15.3619 11.6962 15.5 12 15.5C12.3038 15.5 12.5911 15.3619 12.7809 15.1247L16.7809 10.1247C17.021 9.82453 17.0678 9.41328 16.9013 9.06681C16.7348 8.72035 16.3844 8.5 16 8.5H8.00001Z" />
    </Icon>
  );
}
