// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function Battery25percentIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M21 8C21 6.34315 19.6569 5 18 5H4C2.34315 5 1 6.34315 1 8V16C1 17.6569 2.34315 19 4 19H18C19.6569 19 21 17.6569 21 16C22.1046 16 23 15.1046 23 14V10C23 8.89543 22.1046 8 21 8ZM3 8.5C3 7.67157 3.67157 7 4.5 7H6.5C7.32843 7 8 7.67157 8 8.5V15.5C8 16.3284 7.32843 17 6.5 17H4.5C3.67157 17 3 16.3284 3 15.5V8.5Z" />
    </Icon>
  );
}
