// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function BatteryExclamationIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M21 8C21 6.34315 19.6569 5 18 5H4C2.34315 5 1 6.34315 1 8V16C1 17.6569 2.34315 19 4 19H18C19.6569 19 21 17.6569 21 16C22.1046 16 23 15.1046 23 14V10C23 8.89543 22.1046 8 21 8ZM11 8C11.5523 8 12 8.44772 12 9V11C12 11.5523 11.5523 12 11 12C10.4477 12 10 11.5523 10 11V9C10 8.44772 10.4477 8 11 8ZM12.25 14.5C12.25 15.1904 11.6904 15.75 11 15.75C10.3096 15.75 9.75 15.1904 9.75 14.5C9.75 13.8096 10.3096 13.25 11 13.25C11.6904 13.25 12.25 13.8096 12.25 14.5Z" />
    </Icon>
  );
}
