// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function Battery100percentIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M18 5C19.6569 5 21 6.34315 21 8C22.1046 8 23 8.89543 23 10V14C23 15.1046 22.1046 16 21 16C21 17.6569 19.6569 19 18 19H4C2.34315 19 1 17.6569 1 16V8C1 6.34315 2.34315 5 4 5H18Z" />
    </Icon>
  );
}
