// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function BedSingleIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M7 2H8V5C8 6.10457 8.89543 7 10 7H14C15.1046 7 16 6.10457 16 5V2H17C18.6569 2 20 3.34315 20 5V9.53513C19.4117 9.19479 18.7286 9 18 9H6C5.27143 9 4.58835 9.19479 4 9.53513V5C4 3.34315 5.34315 2 7 2ZM4 13V19C4 20.6569 5.34315 22 7 22H17C18.6569 22 20 20.6569 20 19V13C20 11.8954 19.1046 11 18 11H6C4.89543 11 4 11.8954 4 13ZM10 2H14V5H10V2Z" />
    </Icon>
  );
}
