// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function BlockquoteIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M4 4C4 3.44772 3.55228 3 3 3C2.44772 3 2 3.44772 2 4V20C2 20.5523 2.44772 21 3 21C3.55228 21 4 20.5523 4 20V4ZM18 8C18.5523 8 19 7.55228 19 7C19 6.44772 18.5523 6 18 6L7 6C6.44771 6 6 6.44771 6 7C6 7.55228 6.44771 8 7 8L18 8ZM22 12C22 12.5523 21.5523 13 21 13L7 13C6.44771 13 6 12.5523 6 12C6 11.4477 6.44771 11 7 11L21 11C21.5523 11 22 11.4477 22 12ZM13 18C13.5523 18 14 17.5523 14 17C14 16.4477 13.5523 16 13 16H7C6.44772 16 6 16.4477 6 17C6 17.5523 6.44772 18 7 18H13Z" />
    </Icon>
  );
}
