// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function BoldIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M7 2.5C5.89543 2.5 5 3.39543 5 4.5V12V19.3182C5 20.5232 5.97683 21.5 7.18182 21.5H14.75C17.6495 21.5 20 19.1495 20 16.25C20 13.9975 18.5815 12.0764 16.589 11.3311C17.4644 10.3932 18 9.13414 18 7.75C18 4.85051 15.6495 2.5 12.75 2.5H7ZM12.75 11C14.5449 11 16 9.54493 16 7.75C16 5.95507 14.5449 4.5 12.75 4.5H7V11H12.75ZM7 13V19.3182C7 19.4186 7.0814 19.5 7.18182 19.5H14.75C16.5449 19.5 18 18.0449 18 16.25C18 14.4551 16.5449 13 14.75 13H12.75H7Z" />
    </Icon>
  );
}
