// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function BookmarkIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M6 4C4.34315 4 3 5.34315 3 7V17.5925C3 20.1699 6.03576 21.5475 7.97551 19.8502L12 16.3288L16.0245 19.8502C17.9642 21.5475 21 20.1699 21 17.5925V7C21 5.34315 19.6569 4 18 4H6Z" />
    </Icon>
  );
}
