// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function BookIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M20 4C20 2.89543 19.1046 2 18 2H7C5.34315 2 4 3.34315 4 5V19C4 20.6569 5.34315 22 7 22H18.5C19.0523 22 19.5 21.5523 19.5 21C19.5 20.4477 19.0523 20 18.5 20H7C6.44772 20 6 19.5523 6 19C6 18.4477 6.44772 18 7 18H18C19.1046 18 20 17.1046 20 16L20 4Z" />
    </Icon>
  );
}
