// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function CalendarCheckmarkIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M9 3C9 2.44772 8.55228 2 8 2C7.44772 2 7 2.44772 7 3V4.5H5C3.34315 4.5 2 5.84315 2 7.5V19C2 20.6569 3.34315 22 5 22H19C20.6569 22 22 20.6569 22 19V7.5C22 5.84315 20.6569 4.5 19 4.5H17V3C17 2.44772 16.5523 2 16 2C15.4477 2 15 2.44772 15 3V4.5H9V3ZM16.2071 11.7071C16.5976 11.3166 16.5976 10.6834 16.2071 10.2929C15.8166 9.90237 15.1834 9.90237 14.7929 10.2929L11 14.0858L9.20711 12.2929C8.81658 11.9024 8.18342 11.9024 7.79289 12.2929C7.40237 12.6834 7.40237 13.3166 7.79289 13.7071L10.2929 16.2071C10.6834 16.5976 11.3166 16.5976 11.7071 16.2071L16.2071 11.7071Z" />
    </Icon>
  );
}
