// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function CardsHeartIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M10.4937 5.77823C8.24018 3.72955 4.77487 3.81201 2.62132 5.96556C0.393154 8.19373 0.393156 11.8063 2.62132 14.0345L9.29398 20.7071C10.7891 22.2022 13.2131 22.2022 14.7082 20.7071L21.3809 14.0345C23.609 11.8063 23.609 8.19372 21.3809 5.96556C19.2273 3.81201 15.762 3.72955 13.5084 5.77823L12.0011 7.14855L10.4937 5.77823Z" />
    </Icon>
  );
}
