// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function CheckerboardIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M2.5 5.5C2.5 3.84315 3.84315 2.5 5.5 2.5H14H18.5C20.1569 2.5 21.5 3.84315 21.5 5.5V10V18.5C21.5 20.1569 20.1569 21.5 18.5 21.5H10H5.5C3.84315 21.5 2.5 20.1569 2.5 18.5V14V5.5ZM5.5 11H11V5.5V4.5H5.5C4.94772 4.5 4.5 4.94772 4.5 5.5V11H5.5ZM13 13V18.5V19.5H18.5C19.0523 19.5 19.5 19.0523 19.5 18.5V13H18.5H13Z" />
    </Icon>
  );
}
