// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function ClipboardIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M18 3H15.8293C15.4175 1.83481 14.3062 1 13 1H11C9.69378 1 8.58254 1.83481 8.17071 3H6C4.34315 3 3 4.34315 3 6V19C3 20.6569 4.34315 22 6 22H18C19.6569 22 21 20.6569 21 19V6C21 4.34315 19.6569 3 18 3ZM10 4C10 4.55228 10.4477 5 11 5H13C13.5523 5 14 4.55228 14 4C14 3.44772 13.5523 3 13 3H11C10.4477 3 10 3.44772 10 4ZM7 4C7.55228 4 8 4.44772 8 5C8 6.10457 8.89543 7 10 7H14C15.1046 7 16 6.10457 16 5C16 4.44772 16.4477 4 17 4C17.5523 4 18 4.44772 18 5C18 7.20914 16.2091 9 14 9H10C7.79086 9 6 7.20914 6 5C6 4.44772 6.44772 4 7 4Z" />
    </Icon>
  );
}
