// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function CloudIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M11.5 3.5C8.22273 3.5 5.51194 5.92543 5.06472 9.0792C2.47265 9.52325 0.5 11.7813 0.5 14.5C0.5 17.5376 2.96243 20 6 20H18.5C21.2614 20 23.5 17.7614 23.5 15C23.5 12.2386 21.2614 10 18.5 10C18.3314 10 18.1645 10.0084 18 10.0248L18 10C18 6.41015 15.0899 3.5 11.5 3.5Z" />
    </Icon>
  );
}
