// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function CreditCardIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M4.5 3.5C2.84315 3.5 1.5 4.84315 1.5 6.5V8L22.5 8V6.5C22.5 4.84315 21.1569 3.5 19.5 3.5H4.5ZM1.5 17.5V10L22.5 10V17.5C22.5 19.1569 21.1569 20.5 19.5 20.5H4.5C2.84315 20.5 1.5 19.1569 1.5 17.5ZM6 14C5.44772 14 5 14.4477 5 15C5 15.5523 5.44772 16 6 16H8C8.55228 16 9 15.5523 9 15C9 14.4477 8.55228 14 8 14H6Z" />
    </Icon>
  );
}
