// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function CrossChristianIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M13 3C13 2.44772 12.5523 2 12 2C11.4477 2 11 2.44772 11 3V8H5C4.44771 8 4 8.44772 4 9C4 9.55228 4.44771 10 5 10H11V21C11 21.5523 11.4477 22 12 22C12.5523 22 13 21.5523 13 21V10H19C19.5523 10 20 9.55228 20 9C20 8.44772 19.5523 8 19 8H13V3Z" />
    </Icon>
  );
}
