// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function CrossMedicalCircleIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M1.5 12C1.5 6.20101 6.20101 1.5 12 1.5C17.799 1.5 22.5 6.20101 22.5 12C22.5 17.799 17.799 22.5 12 22.5C6.20101 22.5 1.5 17.799 1.5 12ZM9.75 7.5C9.75 6.80964 10.3096 6.25 11 6.25H13C13.6904 6.25 14.25 6.80964 14.25 7.5V9.75H16.5C17.1904 9.75 17.75 10.3096 17.75 11V13C17.75 13.6904 17.1904 14.25 16.5 14.25H14.25V16.5C14.25 17.1904 13.6904 17.75 13 17.75H11C10.3096 17.75 9.75 17.1904 9.75 16.5V14.25H7.5C6.80964 14.25 6.25 13.6904 6.25 13V11C6.25 10.3096 6.80964 9.75 7.5 9.75H9.75V7.5Z" />
    </Icon>
  );
}
