// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function CrownIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M13.1522 4.32097C12.5525 3.60134 11.4473 3.60134 10.8476 4.32097L6.89671 9.062L3.59391 6.08948C2.58909 5.18514 0.994699 5.96706 1.09456 7.31523L1.79682 16.7957C1.95155 18.8845 3.69139 20.5002 5.78589 20.5002H18.2139C20.3084 20.5002 22.0482 18.8845 22.203 16.7957L22.9052 7.31523C23.0051 5.96705 21.4107 5.18514 20.4059 6.08948L17.1031 9.062L13.1522 4.32097Z" />
    </Icon>
  );
}
