// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function DiamondShapeIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M14.603 2.44001C13.1648 1.00177 10.8329 1.00177 9.39467 2.44001L2.43879 9.39589C1.00055 10.8341 1.00055 13.166 2.43879 14.6042L9.39467 21.5601C10.8329 22.9983 13.1648 22.9983 14.603 21.5601L21.5589 14.6042C22.9971 13.166 22.9971 10.8341 21.5589 9.39589L14.603 2.44001Z" />
    </Icon>
  );
}
