// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function DropletIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M14.0562 2.64978C12.9274 1.47091 11.0726 1.47091 9.94377 2.64978C8.79082 3.85385 7.08579 5.74121 5.66248 7.75821C4.95082 8.76671 4.29498 9.82802 3.81385 10.8685C3.3382 11.8972 3 12.9759 3 14.0002C3 18.9708 7.02944 23.0002 12 23.0002C16.9706 23.0002 21 18.9708 21 14.0002C21 12.9759 20.6618 11.8972 20.1862 10.8685C19.705 9.82802 19.0492 8.76671 18.3375 7.75821C16.9142 5.74121 15.2092 3.85385 14.0562 2.64978Z" />
    </Icon>
  );
}
