// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function EndPointDiamondIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M18.2428 7.29289C17.8522 6.90237 17.2191 6.90237 16.8285 7.29289L13.1213 11.0001H3C2.44772 11.0001 2 11.4478 2 12.0001C2 12.5524 2.44772 13.0001 3 13.0001H13.1215L16.8285 16.7071C17.2191 17.0976 17.8522 17.0976 18.2428 16.7071L22.2428 12.7071C22.6333 12.3166 22.6333 11.6834 22.2428 11.2929L18.2428 7.29289Z" />
    </Icon>
  );
}
