// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function EndPointArrowIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M22.5 11.1341C22.8094 11.3127 23 11.6429 23 12.0001C23 12.3574 22.8094 12.6875 22.5 12.8662L15.75 16.7633C15.4406 16.9419 15.0594 16.9419 14.75 16.7633C14.4406 16.5847 14.25 16.2545 14.25 15.8973V13H3C2.44772 13 2 12.5523 2 12C2 11.4478 2.44772 11 3 11H14.25V8.10303C14.25 7.74576 14.4406 7.41564 14.75 7.237C15.0594 7.05837 15.4406 7.05837 15.75 7.237L22.5 11.1341Z" />
    </Icon>
  );
}
