// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function EndPointArrowReversedIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M12.7319 13H3C2.44772 13 2 12.5523 2 12C2 11.4478 2.44772 11 3 11H12.7322L19.25 7.237C19.5594 7.05837 19.9406 7.05837 20.25 7.237C20.5594 7.41564 20.75 7.74576 20.75 8.10303V15.8973C20.75 16.2545 20.5594 16.5847 20.25 16.7633C19.9406 16.9419 19.5594 16.9419 19.25 16.7633L12.7319 13Z" />
    </Icon>
  );
}
