// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function EndPointCircleIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M13.1115 11C13.5662 8.99601 15.3584 7.5 17.5 7.5C19.9853 7.5 22 9.51472 22 12C22 14.4853 19.9853 16.5 17.5 16.5C15.3584 16.5 13.5662 15.004 13.1115 13H3C2.44772 13 2 12.5523 2 12C2 11.4477 2.44772 11 3 11H13.1115Z" />
    </Icon>
  );
}
