// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function EndPointRoundIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M3 5.33333C3 4.04467 4.04467 3 5.33333 3H12C16.9706 3 21 7.02944 21 12C21 16.9706 16.9706 21 12 21H5.33333C4.04467 21 3 19.9553 3 18.6667V13H12C12.5523 13 13 12.5523 13 12C13 11.4477 12.5523 11 12 11H3V5.33333Z" />
    </Icon>
  );
}
