// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function EuIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M3 5C1.89543 5 1 5.89543 1 7V17C1 18.1046 1.89543 19 3 19H9.5C10.0523 19 10.5 18.5523 10.5 18C10.5 17.4477 10.0523 17 9.5 17H3V13H8.25C8.80228 13 9.25 12.5523 9.25 12C9.25 11.4477 8.80228 11 8.25 11H3V7H9.5C10.0523 7 10.5 6.55228 10.5 6C10.5 5.44772 10.0523 5 9.5 5H3ZM14.5 6C14.5 5.44772 14.0523 5 13.5 5C12.9477 5 12.5 5.44772 12.5 6V13.75C12.5 16.6495 14.8505 19 17.75 19C20.6495 19 23 16.6495 23 13.75V6C23 5.44772 22.5523 5 22 5C21.4477 5 21 5.44772 21 6V13.75C21 15.5449 19.5449 17 17.75 17C15.9551 17 14.5 15.5449 14.5 13.75V6Z" />
    </Icon>
  );
}
