// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function FastForwardIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M4.14692 5.28201C2.82137 4.35412 1 5.30243 1 6.92047V17.0792C1 18.6972 2.82137 19.6455 4.14693 18.7176L11.4031 13.6383C11.6602 13.4583 11.8591 13.2331 12 12.9829V17.0792C12 18.6972 13.8214 19.6455 15.1469 18.7176L22.4031 13.6383C23.5406 12.8421 23.5406 11.1576 22.4031 10.3614L15.1469 5.28201C13.8214 4.35412 12 5.30243 12 6.92047V11.0167C11.8591 10.7666 11.6602 10.5413 11.4031 10.3614L4.14692 5.28201Z" />
    </Icon>
  );
}
