// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function FileIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M3 19C3 20.6569 4.34315 22 6 22H18C19.6569 22 21 20.6569 21 19V12H15C13.3431 12 12 10.6569 12 9V2H6C4.34315 2 3 3.34315 3 5V19ZM14 2.62426V9C14 9.55228 14.4477 10 15 10H20.4538L14 2.62426Z" />
    </Icon>
  );
}
