// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function FileMinusIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M3 16H8C9.65685 16 11 17.3431 11 19C11 20.6569 9.65685 22 8 22H18C19.6569 22 21 20.6569 21 19V12H15C13.3431 12 12 10.6569 12 9V2H6C4.34315 2 3 3.34315 3 5V16ZM14 9V2.62426L20.4538 10H15C14.4477 10 14 9.55228 14 9ZM1 19C1 18.4477 1.44772 18 2 18H8C8.55228 18 9 18.4477 9 19C9 19.5523 8.55228 20 8 20H2C1.44772 20 1 19.5523 1 19Z" />
    </Icon>
  );
}
