// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function FilmStripIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M5 3H4C2.89543 3 2 3.89543 2 5V6H5V3ZM2 8V11H5V8H2ZM2 13V16H5V13H2ZM2 18V19C2 20.1046 2.89543 21 4 21H5V18H2ZM7 21H17V17V13H7V17V21ZM19 21H20C21.1046 21 22 20.1046 22 19V18H19V21ZM22 16V13H19V16H22ZM22 11V8H19V11H22ZM22 6V5C22 3.89543 21.1046 3 20 3H19V6H22ZM17 3H7V7V11H17V7V3Z" />
    </Icon>
  );
}
