// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function FilterAlt2Icon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M4.87108 2.5C2.50473 2.5 1.24334 5.29028 2.80662 7.06673L9.49833 14.6709V21.1893C9.49833 22.7484 11.3833 23.5292 12.4858 22.4268L13.9125 21C14.2876 20.6249 14.4983 20.1162 14.4983 19.5858V14.6747L21.1933 7.06673C22.7566 5.29027 21.4952 2.5 19.1289 2.5H4.87108Z" />
    </Icon>
  );
}
