// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function FolderMinusIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M4 3C2.34315 3 1 4.34315 1 6V18C1 19.6569 2.34315 21 4 21H13.7639C13.2889 20.4692 13 19.7684 13 19C13 17.3431 14.3431 16 16 16H22C22.3506 16 22.6872 16.0602 23 16.1707V9C23 7.34315 21.6569 6 20 6H12.5352L11.1289 3.8906C10.758 3.3342 10.1335 3 9.46482 3H4ZM16 18C15.4477 18 15 18.4477 15 19C15 19.5523 15.4477 20 16 20H22C22.5523 20 23 19.5523 23 19C23 18.4477 22.5523 18 22 18H16Z" />
    </Icon>
  );
}
