// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function FolderSlashCircleAlt2Icon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M1 6C1 4.34315 2.34315 3 4 3H9.46482C10.1335 3 10.758 3.3342 11.1289 3.8906L12.5352 6H20C21.6569 6 23 7.34315 23 9V18C23 19.6569 21.6569 21 20 21H4C2.34315 21 1 19.6569 1 18V6ZM12 10.5C10.3431 10.5 9 11.8431 9 13.5C9 13.9631 9.10495 14.4018 9.29237 14.7934L13.2934 10.7924C12.9018 10.605 12.4631 10.5 12 10.5ZM12 16.5C11.5369 16.5 11.0982 16.395 10.7066 16.2076L14.7076 12.2066C14.895 12.5982 15 13.0369 15 13.5C15 15.1569 13.6569 16.5 12 16.5ZM7 13.5C7 10.7386 9.23858 8.5 12 8.5C14.7614 8.5 17 10.7386 17 13.5C17 16.2614 14.7614 18.5 12 18.5C9.23858 18.5 7 16.2614 7 13.5Z" />
    </Icon>
  );
}
