// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function FolderIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M4.5 3C2.84315 3 1.5 4.34315 1.5 6V17.5C1.5 19.1569 2.84315 20.5 4.5 20.5H19.5C21.1569 20.5 22.5 19.1569 22.5 17.5V9C22.5 7.34315 21.1569 6 19.5 6H12.5352L11.1289 3.8906C10.758 3.3342 10.1335 3 9.46482 3H4.5Z" />
    </Icon>
  );
}
