// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function FrameIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M18 3C18 2.44772 17.5523 2 17 2C16.4477 2 16 2.44772 16 3V6L8 6V3C8 2.44772 7.55228 2 7 2C6.44772 2 6 2.44772 6 3V6L3 6C2.44772 6 2 6.44771 2 7C2 7.55228 2.44772 8 3 8H6V16H3C2.44772 16 2 16.4477 2 17C2 17.5523 2.44772 18 3 18H6V21C6 21.5523 6.44772 22 7 22C7.55228 22 8 21.5523 8 21V18L16 18V21C16 21.5523 16.4477 22 17 22C17.5523 22 18 21.5523 18 21V18H21C21.5523 18 22 17.5523 22 17C22 16.4477 21.5523 16 21 16H18V8H21C21.5523 8 22 7.55228 22 7C22 6.44772 21.5523 6 21 6H18V3ZM16 8H8V16L16 16V8Z" />
    </Icon>
  );
}
