// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function GitMergeIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M3 5.5C3 7.08551 4.05426 8.42479 5.5 8.85506V15.1449C4.05426 15.5752 3 16.9145 3 18.5C3 20.433 4.567 22 6.5 22C8.433 22 10 20.433 10 18.5C10 16.9145 8.94574 15.5752 7.5 15.1449V12.4705C8.80408 13.774 10.8846 14.8225 14.1389 14.9796C14.5627 16.4358 15.9071 17.5 17.5 17.5C19.433 17.5 21 15.933 21 14C21 12.067 19.433 10.5 17.5 10.5C15.9226 10.5 14.5889 11.5435 14.1516 12.9779C10.7561 12.796 9.15987 11.5251 8.37852 10.422C7.97021 9.84554 7.75018 9.26734 7.63212 8.81285C9.00953 8.34226 10 7.0368 10 5.5C10 3.567 8.433 2 6.5 2C4.567 2 3 3.567 3 5.5Z" />
    </Icon>
  );
}
