// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function GitCommitIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M8.64494 11L3 11C2.44772 11 2 11.4477 2 12C2 12.5523 2.44772 13 3 13L8.64494 13C9.07521 14.4457 10.4145 15.5 12 15.5C13.5855 15.5 14.9248 14.4457 15.3551 13L21 13C21.5523 13 22 12.5523 22 12C22 11.4477 21.5523 11 21 11L15.3551 11C14.9248 9.55426 13.5855 8.5 12 8.5C10.4145 8.5 9.07521 9.55426 8.64494 11Z" />
    </Icon>
  );
}
