// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function GridColumns2Icon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M11 4.5C11 3.39543 10.1046 2.5 9 2.5H4.5C3.39543 2.5 2.5 3.39543 2.5 4.5V19.5C2.5 20.6046 3.39543 21.5 4.5 21.5H9C10.1046 21.5 11 20.6046 11 19.5V4.5ZM13 19.5C13 20.6046 13.8954 21.5 15 21.5H19.5C20.6046 21.5 21.5 20.6046 21.5 19.5V4.5C21.5 3.39543 20.6046 2.5 19.5 2.5H15C13.8954 2.5 13 3.39543 13 4.5V19.5Z" />
    </Icon>
  );
}
