// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function GridRows3Icon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M21.5 4.5C21.5 3.39543 20.6046 2.5 19.5 2.5H4.5C3.39543 2.5 2.5 3.39543 2.5 4.5V5.25C2.5 6.35457 3.39543 7.25 4.5 7.25L19.5 7.25C20.6046 7.25 21.5 6.35457 21.5 5.25V4.5ZM21.5 11.6504C21.5 10.5458 20.6046 9.65039 19.5 9.65039L4.5 9.65039C3.39543 9.65039 2.5 10.5458 2.5 11.6504V12.4004C2.5 13.505 3.39543 14.4004 4.5 14.4004L19.5 14.4004C20.6046 14.4004 21.5 13.505 21.5 12.4004V11.6504ZM21.5 18.75C21.5 17.6454 20.6046 16.75 19.5 16.75L4.5 16.75C3.39543 16.75 2.5 17.6454 2.5 18.75V19.5C2.5 20.6046 3.39543 21.5 4.5 21.5H19.5C20.6046 21.5 21.5 20.6046 21.5 19.5V18.75Z" />
    </Icon>
  );
}
