// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function GridRows2Icon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M21.5 4.5C21.5 3.39543 20.6046 2.5 19.5 2.5H4.5C3.39543 2.5 2.5 3.39543 2.5 4.5V9C2.5 10.1046 3.39543 11 4.5 11L19.5 11C20.6046 11 21.5 10.1046 21.5 9V4.5ZM21.5 15C21.5 13.8954 20.6046 13 19.5 13L4.5 13C3.39543 13 2.5 13.8954 2.5 15V19.5C2.5 20.6046 3.39543 21.5 4.5 21.5H19.5C20.6046 21.5 21.5 20.6046 21.5 19.5V15Z" />
    </Icon>
  );
}
