// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function GridRows2Columns2Icon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M4.5 2.5C3.39543 2.5 2.5 3.39543 2.5 4.5V9C2.5 10.1046 3.39543 11 4.5 11H9C10.1046 11 11 10.1046 11 9V4.5C11 3.39543 10.1046 2.5 9 2.5H4.5ZM15 2.5C13.8954 2.5 13 3.39543 13 4.5V9C13 10.1046 13.8954 11 15 11H19.5C20.6046 11 21.5 10.1046 21.5 9V4.5C21.5 3.39543 20.6046 2.5 19.5 2.5H15ZM15 13C13.8954 13 13 13.8954 13 15V19.5C13 20.6046 13.8954 21.5 15 21.5H19.5C20.6046 21.5 21.5 20.6046 21.5 19.5V15C21.5 13.8954 20.6046 13 19.5 13H15ZM4.5 13C3.39543 13 2.5 13.8954 2.5 15V19.5C2.5 20.6046 3.39543 21.5 4.5 21.5H9C10.1046 21.5 11 20.6046 11 19.5V15C11 13.8954 10.1046 13 9 13H4.5Z" />
    </Icon>
  );
}
