// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function HeadphonesIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M2 17V15V12C2 6.47715 6.47715 2 12 2C17.5228 2 22 6.47715 22 12V15V17V18C22 20.2091 20.2091 22 18 22C15.7909 22 14 20.2091 14 18V15C14 12.7909 15.7909 11 18 11C18.7229 11 19.401 11.1918 19.9863 11.5272C19.7416 7.32902 16.2596 4 12 4C7.74044 4 4.25841 7.32902 4.01374 11.5272C4.59897 11.1918 5.27709 11 6 11C8.20914 11 10 12.7909 10 15V18C10 20.2091 8.20914 22 6 22C3.79086 22 2 20.2091 2 18V17Z" />
    </Icon>
  );
}
