// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function HeadsetIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M7 9C7 6.23858 9.23858 4 12 4C14.7614 4 17 6.23858 17 9V10V12V16V17C17 17.9956 16.2725 18.8213 15.3202 18.9745C14.9012 17.8227 13.7967 17 12.5 17H11.5C9.84315 17 8.5 18.3431 8.5 20C8.5 21.6569 9.84315 23 11.5 23H12.5C13.8114 23 14.9262 22.1586 15.3341 20.9862C17.3869 20.8165 19 19.0966 19 17H20C21.6569 17 23 15.6569 23 14V12C23 10.3431 21.6569 9 20 9L19 9C19 5.13401 15.866 2 12 2C8.13401 2 5 5.13401 5 9H4C2.34315 9 1 10.3431 1 12V14C1 15.6569 2.34315 17 4 17H6C6.55228 17 7 16.5523 7 16V12V10V9Z" />
    </Icon>
  );
}
