// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function HexagonIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M13.5001 1.71149C12.5719 1.1756 11.4283 1.1756 10.5001 1.71149L3.83984 5.55679C2.91164 6.09269 2.33984 7.08307 2.33984 8.15487V15.8455C2.33984 16.9173 2.91164 17.9076 3.83984 18.4435L10.5001 22.2888C11.4283 22.8247 12.5719 22.8247 13.5001 22.2888L20.1604 18.4435C21.0886 17.9076 21.6604 16.9173 21.6604 15.8455V8.15487C21.6604 7.08307 21.0886 6.09269 20.1604 5.55679L13.5001 1.71149Z" />
    </Icon>
  );
}
