// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function HouseIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M13.8418 3.16564C12.7585 2.32304 11.2415 2.32304 10.1582 3.16563L3.15818 8.61008C2.42742 9.17845 2 10.0524 2 10.9781V19C2 20.6568 3.34315 22 5 22H7C8.65685 22 10 20.6568 10 19V17C10 16.4477 10.4477 16 11 16H13C13.5523 16 14 16.4477 14 17V19C14 20.6568 15.3431 22 17 22H19C20.6569 22 22 20.6568 22 19V10.9781C22 10.0524 21.5726 9.17845 20.8418 8.61008L13.8418 3.16564Z" />
    </Icon>
  );
}
