// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function ItalicIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M9 3.5C9 2.94772 9.44772 2.5 10 2.5H18C18.5523 2.5 19 2.94772 19 3.5C19 4.05228 18.5523 4.5 18 4.5H14.792L11.2626 19.5H14C14.5523 19.5 15 19.9477 15 20.5C15 21.0523 14.5523 21.5 14 21.5H6C5.44772 21.5 5 21.0523 5 20.5C5 19.9477 5.44772 19.5 6 19.5H9.20798L12.7374 4.5H10C9.44772 4.5 9 4.05228 9 3.5Z" />
    </Icon>
  );
}
