// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function KeyAlt2Icon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M13 12C13 9.79086 14.7909 8 17 8C19.2091 8 21 9.79086 21 12C21 14.2091 19.2091 16 17 16C14.7909 16 13 14.2091 13 12ZM11.083 13C11.559 15.8377 14.027 18 17 18C20.3137 18 23 15.3137 23 12C23 8.68629 20.3137 6 17 6C14.027 6 11.559 8.16229 11.083 11H5.5H3C1.89543 11 1 11.8954 1 13V15.5C1 16.0523 1.44772 16.5 2 16.5C2.55228 16.5 3 16.0523 3 15.5V13H4.5V14.5C4.5 15.0523 4.94772 15.5 5.5 15.5C6.05228 15.5 6.5 15.0523 6.5 14.5V13H11.083Z" />
    </Icon>
  );
}
