// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function LaptopIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M3.00008 6.5C3.00008 4.84315 4.34323 3.5 6.00008 3.5H18.0001C19.6569 3.5 21.0001 4.84315 21.0001 6.5V14.223L22.9489 17.471C23.7487 18.8041 22.7885 20.5 21.2339 20.5H2.76627C1.21168 20.5 0.251459 18.8041 1.05129 17.471L3.00008 14.223V6.5ZM5.00008 13.5H19.0001V6.5C19.0001 5.94772 18.5524 5.5 18.0001 5.5H6.00008C5.4478 5.5 5.00008 5.94772 5.00008 6.5V13.5Z" />
    </Icon>
  );
}
