// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function LockUnlockedIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M11.883 2C9.73088 2 7.82019 3.37715 7.13962 5.41886L7.05132 5.68377C6.87667 6.20772 7.15983 6.77404 7.68377 6.94868C8.20772 7.12333 8.77404 6.84017 8.94868 6.31623L9.03699 6.05132C9.44533 4.82629 10.5917 4 11.883 4H12C13.6569 4 15 5.34315 15 7V9H7C4.79086 9 3 10.7909 3 13V18C3 20.2091 4.79086 22 7 22H17C19.2091 22 21 20.2091 21 18V13C21 10.7909 19.2091 9 17 9V7C17 4.23858 14.7614 2 12 2H11.883Z" />
    </Icon>
  );
}
