// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function LockLockedIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M12 2C9.23858 2 7 4.23858 7 7V9C4.79086 9 3 10.7909 3 13V18C3 20.2091 4.79086 22 7 22H17C19.2091 22 21 20.2091 21 18V13C21 10.7909 19.2091 9 17 9V7C17 4.23858 14.7614 2 12 2ZM15 9V7C15 5.34315 13.6569 4 12 4C10.3431 4 9 5.34315 9 7V9H15Z" />
    </Icon>
  );
}
