// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function LogoGooglePlayIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M20.875 9.61852C22.7083 10.677 22.7083 13.3232 20.875 14.3817L17.6549 16.2408L13.4142 12.0001L17.6549 7.75938L20.875 9.61852ZM15.8617 6.72411L8.125 2.2573C6.80914 1.49759 5.25717 1.96475 4.48589 3.07173L12 10.5858L15.8617 6.72411ZM4 5.41427L10.5858 12.0001L4 18.5858V5.41427ZM4.48587 20.9284C5.25714 22.0354 6.80913 22.5026 8.125 21.7429L15.8618 17.276L12 13.4143L4.48587 20.9284Z" />
    </Icon>
  );
}
