// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function LogoSubstackIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M4 3C3.44772 3 3 3.44772 3 4C3 4.55228 3.44772 5 4 5H20C20.5523 5 21 4.55228 21 4C21 3.44772 20.5523 3 20 3H4ZM3 7.5C3 6.94772 3.44772 6.5 4 6.5H20C20.5523 6.5 21 6.94772 21 7.5C21 8.05228 20.5523 8.5 20 8.5H4C3.44772 8.5 3 8.05228 3 7.5ZM4 10C3.44772 10 3 10.4477 3 11V19.099C3 20.7093 4.80605 21.6594 6.13306 20.7471L12 16.7135L17.8669 20.7471C19.1939 21.6594 21 20.7093 21 19.099V11C21 10.4477 20.5523 10 20 10H4Z" />
    </Icon>
  );
}
