// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function LogoTwitchIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M2.5 4C2.5 2.89543 3.39543 2 4.5 2H19.5C20.6046 2 21.5 2.89543 21.5 4V14C21.5 14.2652 21.3946 14.5196 21.2071 14.7071L17.2071 18.7071C17.0196 18.8946 16.7652 19 16.5 19H12.4142L9.56066 21.8536C8.61571 22.7985 7 22.1292 7 20.7929V19H4.5C3.39543 19 2.5 18.1046 2.5 17V4ZM11 7C11.5523 7 12 7.44772 12 8V12C12 12.5523 11.5523 13 11 13C10.4477 13 10 12.5523 10 12V8C10 7.44772 10.4477 7 11 7ZM16 7C16.5523 7 17 7.44772 17 8V12C17 12.5523 16.5523 13 16 13C15.4477 13 15 12.5523 15 12V8C15 7.44772 15.4477 7 16 7Z" />
    </Icon>
  );
}
