// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function LogoReplitIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M4 7.5V4C4 2.89543 4.89543 2 6 2H10.5C11.6046 2 12.5 2.89543 12.5 4V8.25L18 8.25C19.1046 8.25 20 9.14543 20 10.25V13.75C20 14.8546 19.1046 15.75 18 15.75H12.5V20C12.5 21.1046 11.6046 22 10.5 22H6C4.89543 22 4 21.1046 4 20V16.5C4 15.3954 4.89543 14.5 6 14.5H11.5V9.5L6 9.5C4.89543 9.5 4 8.60457 4 7.5Z" />
    </Icon>
  );
}
