// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function LogoFramerMotionIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M4.70711 3.29292C4.42111 3.00692 3.99099 2.92137 3.61732 3.07615C3.24364 3.23093 3 3.59557 3 4.00003V20C3 20.4045 3.24364 20.7691 3.61732 20.9239C3.99099 21.0787 4.42111 20.9931 4.70711 20.7071L8 17.4142L11.2929 20.7071C11.6834 21.0977 12.3166 21.0977 12.7071 20.7071L16 17.4142L19.2929 20.7071C19.5789 20.9931 20.009 21.0787 20.3827 20.9239C20.7564 20.7691 21 20.4045 21 20V4.00003C21 3.59557 20.7564 3.23093 20.3827 3.07615C20.009 2.92137 19.5789 3.00692 19.2929 3.29292L12 10.5858L4.70711 3.29292Z" />
    </Icon>
  );
}
