// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function LogoMicrosoftIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M11 2.5H4.5C3.39543 2.5 2.5 3.39543 2.5 4.5V11H11V2.5ZM2.5 13V19.5C2.5 20.6046 3.39543 21.5 4.5 21.5H11V13H2.5ZM13 21.5H19.5C20.6046 21.5 21.5 20.6046 21.5 19.5V13H13V21.5ZM21.5 11H13V2.5H19.5C20.6046 2.5 21.5 3.39543 21.5 4.5V11Z" />
    </Icon>
  );
}
