// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function LogoFramerIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M6.00005 2C5.58157 2 5.20735 2.26057 5.06216 2.65305C4.91697 3.04554 5.03153 3.48692 5.34926 3.75926L10.2968 8H6.00005C5.44776 8 5.00005 8.44772 5.00005 9V15C5.00005 15.2652 5.1054 15.5196 5.29294 15.7071L11.2929 21.7071C11.5789 21.9931 12.0091 22.0787 12.3827 21.9239C12.7564 21.7691 13 21.4045 13 21V16H18C18.4185 16 18.7927 15.7394 18.9379 15.3469C19.0831 14.9545 18.9686 14.5131 18.6508 14.2407L13.7033 10H18C18.5523 10 19 9.55228 19 9V3C19 2.44772 18.5523 2 18 2H6.00005Z" />
    </Icon>
  );
}
