// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function MinusCircleIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M2 12C2 6.47715 6.47715 2 12 2C17.5228 2 22 6.47715 22 12C22 17.5228 17.5228 22 12 22C6.47715 22 2 17.5228 2 12ZM17 13C17.5523 13 18 12.5523 18 12C18 11.4477 17.5523 11 17 11L7 11C6.44771 11 6 11.4477 6 12C6 12.5523 6.44771 13 7 13L17 13Z" />
    </Icon>
  );
}
