// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function MinusSquareIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M3 6C3 4.34315 4.34315 3 6 3H18C19.6569 3 21 4.34315 21 6V18C21 19.6569 19.6569 21 18 21H6C4.34315 21 3 19.6569 3 18V6ZM17 13C17.5523 13 18 12.5523 18 12C18 11.4477 17.5523 11 17 11L7 11C6.44771 11 6 11.4477 6 12C6 12.5523 6.44771 13 7 13L17 13Z" />
    </Icon>
  );
}
