// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function MugIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M1 6C1 4.61929 2.11929 3.5 3.5 3.5H15C16.3807 3.5 17.5 4.61929 17.5 6V6.5H18.5C20.9853 6.5 23 8.51472 23 11C23 13.4853 20.9853 15.5 18.5 15.5H17.2101C16.3496 18.3915 13.671 20.5 10.5 20.5H8C4.13401 20.5 1 17.366 1 13.5V6ZM17.5 13.5H18.5C19.8807 13.5 21 12.3807 21 11C21 9.61929 19.8807 8.5 18.5 8.5H17.5V13.5Z" />
    </Icon>
  );
}
