// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function MushroomIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M21.4292 9.94656C21.6069 11.4112 20.2962 12.5 18.8208 12.5H13.83H10.1701H5.17959C3.70417 12.5 2.39344 11.4112 2.57114 9.94656C3.13025 5.33783 7.11336 1.5 12.0002 1.5C16.887 1.5 20.8701 5.33783 21.4292 9.94656ZM9.79514 14.5L8.97792 18.8585C8.62311 20.7508 10.0748 22.5 12.0001 22.5C13.9253 22.5 15.377 20.7508 15.0222 18.8585L14.205 14.5H9.79514Z" />
    </Icon>
  );
}
