// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function PassportBiometricIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M1.5 6.5C1.5 4.84315 2.84315 3.5 4.5 3.5H19.5C21.1569 3.5 22.5 4.84315 22.5 6.5V11H16.3885C15.9338 8.99601 14.1416 7.5 12 7.5C9.85841 7.5 8.06624 8.99601 7.61151 11L1.5 11V6.5ZM1.5 13V17.5C1.5 19.1569 2.84315 20.5 4.5 20.5H19.5C21.1569 20.5 22.5 19.1569 22.5 17.5V13H16.3885C15.9338 15.004 14.1416 16.5 12 16.5C9.85841 16.5 8.06624 15.004 7.61151 13L1.5 13ZM9.5 12C9.5 10.6193 10.6193 9.5 12 9.5C13.3807 9.5 14.5 10.6193 14.5 12C14.5 13.3807 13.3807 14.5 12 14.5C10.6193 14.5 9.5 13.3807 9.5 12Z" />
    </Icon>
  );
}
