// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function PauseCircleIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M2 12C2 6.47715 6.47715 2 12 2C17.5228 2 22 6.47715 22 12C22 17.5228 17.5228 22 12 22C6.47715 22 2 17.5228 2 12ZM7 9C7 8.17157 7.67157 7.5 8.5 7.5H9.5C10.3284 7.5 11 8.17157 11 9V15C11 15.8284 10.3284 16.5 9.5 16.5H8.5C7.67157 16.5 7 15.8284 7 15V9ZM13 9C13 8.17157 13.6716 7.5 14.5 7.5H15.5C16.3284 7.5 17 8.17157 17 9V15C17 15.8284 16.3284 16.5 15.5 16.5H14.5C13.6716 16.5 13 15.8284 13 15V9Z" />
    </Icon>
  );
}
