// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function PentagonIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M13.7633 2.29512C12.7118 1.53118 11.288 1.53119 10.2366 2.29512L2.83939 7.66949C1.78793 8.43342 1.34795 9.78752 1.74957 11.0236L4.57505 19.7195C4.97667 20.9556 6.12854 21.7925 7.42822 21.7925H16.5716C17.8713 21.7925 19.0232 20.9556 19.4248 19.7195L22.2503 11.0236C22.6519 9.78752 22.2119 8.43342 21.1605 7.66949L13.7633 2.29512Z" />
    </Icon>
  );
}
