// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function PinAlt2Icon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M6 7C6 3.68629 8.68629 1 12 1C15.3137 1 18 3.68629 18 7C18 9.973 15.8377 12.441 13 12.917V22C13 22.5523 12.5523 23 12 23C11.4477 23 11 22.5523 11 22V12.917C8.16229 12.441 6 9.973 6 7Z" />
    </Icon>
  );
}
