// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function PlayIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M8.1094 2.2045C6.78029 1.31842 5 2.27121 5 3.8686V20.1316C5 21.729 6.78029 22.6817 8.1094 21.7957L20.3066 13.6642C21.4941 12.8725 21.4941 11.1276 20.3066 10.336L8.1094 2.2045Z" />
    </Icon>
  );
}
