// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function PlayCircleIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M2 12C2 6.47715 6.47715 2 12 2C17.5228 2 22 6.47715 22 12C22 17.5228 17.5228 22 12 22C6.47715 22 2 17.5228 2 12ZM8.75 8.4574C8.75 7.034 10.3589 6.20603 11.5172 7.03337L16.4768 10.576C17.4539 11.2739 17.4539 12.7261 16.4768 13.424L11.5172 16.9667C10.3589 17.794 8.75 16.966 8.75 15.5426V8.4574Z" />
    </Icon>
  );
}
