// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function PopsicleIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M11 1C7.68629 1 5 3.68629 5 7V13.75C5 15.4069 6.34315 16.75 8 16.75H10.0155H13.9845H16C17.6569 16.75 19 15.4069 19 13.75V7C19 3.68629 16.3137 1 13 1H11ZM10.75 7C10.75 6.44772 10.3023 6 9.75 6C9.19772 6 8.75 6.44772 8.75 7V12.5C8.75 13.0523 9.19772 13.5 9.75 13.5C10.3023 13.5 10.75 13.0523 10.75 12.5V7ZM15.25 7C15.25 6.44772 14.8023 6 14.25 6C13.6977 6 13.25 6.44772 13.25 7V12.5C13.25 13.0523 13.6977 13.5 14.25 13.5C14.8023 13.5 15.25 13.0523 15.25 12.5V7ZM10 21V18.75H14V21C14 22.1046 13.1046 23 12 23C10.8954 23 10 22.1046 10 21Z" />
    </Icon>
  );
}
