// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function RingIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M8.26761 1.5C7.93326 1.5 7.62103 1.6671 7.43556 1.9453L6.85511 2.81597C6.55367 3.26814 6.66851 3.87827 7.1137 4.1899L10.028 6.22992C6.28452 7.11923 3.5 10.4844 3.5 14.5C3.5 19.1944 7.30558 23 12 23C16.6944 23 20.5 19.1944 20.5 14.5C20.5 10.4844 17.7155 7.11925 13.972 6.22993L16.8863 4.1899C17.3315 3.87827 17.4464 3.26814 17.1449 2.81597L16.5645 1.9453C16.379 1.6671 16.0668 1.5 15.7324 1.5H8.26761ZM12 8C8.41015 8 5.5 10.9101 5.5 14.5C5.5 18.0899 8.41015 21 12 21C15.5899 21 18.5 18.0899 18.5 14.5C18.5 10.9101 15.5899 8 12 8Z" />
    </Icon>
  );
}
