// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function SelectionIntersectIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M8 5.5C8 3.567 9.567 2 11.5 2H18.5C20.433 2 22 3.567 22 5.5V12.5C22 14.433 20.433 16 18.5 16H16V18.5C16 20.433 14.433 22 12.5 22H5.5C3.567 22 2 20.433 2 18.5V11.5C2 9.567 3.567 8 5.5 8H8V5.5ZM18.5 14H16V11.5C16 9.567 14.433 8 12.5 8H10V5.5C10 4.67157 10.6716 4 11.5 4H18.5C19.3284 4 20 4.67157 20 5.5V12.5C20 13.3284 19.3284 14 18.5 14ZM8 12.5V10H5.5C4.67157 10 4 10.6716 4 11.5V18.5C4 19.3284 4.67157 20 5.5 20H12.5C13.3284 20 14 19.3284 14 18.5V16H11.5C9.567 16 8 14.433 8 12.5Z" />
    </Icon>
  );
}
