// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function SelectionSubtractIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M11.5 2C9.567 2 8 3.567 8 5.5V8H5.5C3.567 8 2 9.567 2 11.5V18.5C2 20.433 3.567 22 5.5 22H12.5C14.433 22 16 20.433 16 18.5V16H18.5C20.433 16 22 14.433 22 12.5V5.5C22 3.567 20.433 2 18.5 2H11.5ZM10 5.5C10 4.67157 10.6716 4 11.5 4H18.5C19.3284 4 20 4.67157 20 5.5V12.5C20 13.3284 19.3284 14 18.5 14H11.5C10.6716 14 10 13.3284 10 12.5V5.5Z" />
    </Icon>
  );
}
