// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function SelectionUnionIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M11.5 2C9.567 2 8 3.567 8 5.5V8H5.5C3.567 8 2 9.567 2 11.5V18.5C2 20.433 3.567 22 5.5 22H12.5C14.433 22 16 20.433 16 18.5V16H18.5C20.433 16 22 14.433 22 12.5V5.5C22 3.567 20.433 2 18.5 2H11.5Z" />
    </Icon>
  );
}
