// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function SendIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M21.9588 4.22068C22.43 2.86992 21.1694 1.55515 19.8 1.96916L3.30692 6.95543C1.23592 7.58154 1.1558 10.4843 3.18912 11.2237L10.1714 13.7627L11.9755 20.3775C12.557 22.5097 15.5427 22.6133 16.2706 20.5266L21.9588 4.22068ZM17.707 7.70705C18.0976 7.31652 18.0976 6.68336 17.707 6.29283C17.3165 5.90231 16.6834 5.90231 16.2928 6.29283L11.7928 10.7928C11.4023 11.1834 11.4023 11.8165 11.7928 12.207C12.1834 12.5976 12.8165 12.5976 13.207 12.207L17.707 7.70705Z" />
    </Icon>
  );
}
