// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function SidebarIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M6 4C3.79086 4 2 5.79086 2 8V16C2 18.2091 3.79086 20 6 20H18C20.2091 20 22 18.2091 22 16V8C22 5.79086 20.2091 4 18 4H6ZM4 8C4 6.89543 4.89543 6 6 6H8V18H6C4.89543 18 4 17.1046 4 16V8ZM10 18H18C19.1046 18 20 17.1046 20 16V8C20 6.89543 19.1046 6 18 6H10V18Z" />
    </Icon>
  );
}
