// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function SkipBackwardIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M21 4.8314C21 3.24906 19.2495 2.29338 17.9185 3.14904L6.76774 10.3174C6.40348 10.5515 6.14757 10.8744 6 11.2333L6 3.99976C6 3.44747 5.55229 2.99976 5 2.99976C4.44772 2.99976 4 3.44747 4 3.99976V19.9998C4 20.552 4.44772 20.9998 5 20.9998C5.55228 20.9998 6 20.552 6 19.9998L6 12.7662C6.14757 13.125 6.40348 13.4479 6.76774 13.6821L17.9185 20.8504C19.2495 21.7061 21 20.7504 21 19.1681V4.8314Z" />
    </Icon>
  );
}
