// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function SkipForwardIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M3 4.8314C3 3.24906 4.75049 2.29338 6.08152 3.14904L17.2323 10.3174C17.5965 10.5515 17.8524 10.8744 18 11.2333V3.99976C18 3.44747 18.4477 2.99976 19 2.99976C19.5523 2.99976 20 3.44747 20 3.99976V19.9998C20 20.552 19.5523 20.9998 19 20.9998C18.4477 20.9998 18 20.552 18 19.9998V12.7662C17.8524 13.125 17.5965 13.4479 17.2323 13.6821L6.08152 20.8504C4.75049 21.7061 3 20.7504 3 19.1681V4.8314Z" />
    </Icon>
  );
}
