// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function SlashCircleIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M4 12C4 7.58172 7.58172 4 12 4C13.8487 4 15.551 4.62708 16.9056 5.68014L5.68014 16.9056C4.62708 15.551 4 13.8487 4 12ZM7.09436 18.3199C8.44904 19.3729 10.1513 20 12 20C16.4183 20 20 16.4183 20 12C20 10.1513 19.3729 8.44904 18.3199 7.09436L7.09436 18.3199ZM12 2C6.47715 2 2 6.47715 2 12C2 17.5228 6.47715 22 12 22C17.5228 22 22 17.5228 22 12C22 6.47715 17.5228 2 12 2Z" />
    </Icon>
  );
}
