// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function SmartphoneIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M8 1C5.79086 1 4 2.79086 4 5V19C4 21.2091 5.79086 23 8 23H16C18.2091 23 20 21.2091 20 19V5C20 2.79086 18.2091 1 16 1H8ZM9 4C9 3.44772 9.44772 3 10 3L14 3C14.5523 3 15 3.44772 15 4C15 4.55229 14.5523 5 14 5L10 5C9.44772 5 9 4.55228 9 4ZM13.5 18.5C13.5 19.3284 12.8284 20 12 20C11.1716 20 10.5 19.3284 10.5 18.5C10.5 17.6716 11.1716 17 12 17C12.8284 17 13.5 17.6716 13.5 18.5Z" />
    </Icon>
  );
}
