// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function SockIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M9 2C7.89543 2 7 2.89543 7 4V10.8034C7 10.967 6.93134 11.123 6.81075 11.2336L4.78599 13.0896C2.47927 15.2041 2.40081 18.815 4.61351 21.0277C6.75996 23.1742 10.24 23.1742 12.3865 21.0277L15.6569 17.7574C17.1571 16.2571 18 14.2222 18 12.1005V4C18 2.89543 17.1046 2 16 2H9ZM10 4C9.44772 4 9 4.44772 9 5C9 5.55228 9.44772 6 10 6L15 6C15.5523 6 16 5.55229 16 5C16 4.44772 15.5523 4 15 4L10 4Z" />
    </Icon>
  );
}
