// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function SodaIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M6.5 2C6.5 1.44772 6.94772 1 7.5 1H9.38197C10.1395 1 10.832 1.428 11.1708 2.10557L12.618 5H19C19.8284 5 20.5 5.67157 20.5 6.5V7C20.5 7.7046 20.0142 8.29572 19.3593 8.4567L19.3549 8.5H4.64496L4.64062 8.45667C3.98575 8.29566 3.5 7.70456 3.5 7V6.5C3.5 5.67157 4.17157 5 5 5H10.382L9.38197 3H7.5C6.94772 3 6.5 2.55228 6.5 2ZM4.84496 10.5L5.82481 20.2985C5.97817 21.8321 7.26866 23 8.80992 23H15.19C16.7312 23 18.0217 21.8321 18.1751 20.2985L19.1549 10.5H4.84496ZM12 13.5C10.3431 13.5 9 14.8431 9 16.5C9 18.1569 10.3431 19.5 12 19.5C13.6569 19.5 15 18.1569 15 16.5C15 14.8431 13.6569 13.5 12 13.5Z" />
    </Icon>
  );
}
