// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function StickyNoteIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M2 6C2 4.34315 3.34315 3 5 3H19C20.6569 3 22 4.34315 22 6V11H16C14.3431 11 13 12.3431 13 14V21H5C3.34315 21 2 19.6569 2 18V6ZM15 20.3757L21.4538 13H16C15.4477 13 15 13.4477 15 14V20.3757Z" />
    </Icon>
  );
}
