// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function StopwatchIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M8 2C8 1.44772 8.44772 1 9 1H15C15.5523 1 16 1.44772 16 2C16 2.55228 15.5523 3 15 3H13V5.05493C14.7359 5.24682 16.3229 5.93238 17.6177 6.9681L19.2929 5.29289C19.6834 4.90237 20.3166 4.90237 20.7071 5.29289C21.0976 5.68342 21.0976 6.31658 20.7071 6.70711L19.0319 8.38231C20.2635 9.92198 21 11.875 21 14C21 18.9706 16.9706 23 12 23C7.02944 23 3 18.9706 3 14C3 9.36745 6.50005 5.55237 11 5.05493V3H9C8.44772 3 8 2.55228 8 2ZM13 8C13 7.44772 12.5523 7 12 7C11.4477 7 11 7.44772 11 8V14C11 14.5523 11.4477 15 12 15C12.5523 15 13 14.5523 13 14V8Z" />
    </Icon>
  );
}
