// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function SuitcaseIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M13.5 2C15.1569 2 16.5 3.34315 16.5 5V6H19.5C21.1569 6 22.5 7.34315 22.5 9V18.5C22.5 20.1569 21.1569 21.5 19.5 21.5H4.5C2.84315 21.5 1.5 20.1569 1.5 18.5V9C1.5 7.34314 2.84315 6 4.5 6H7.5V5C7.5 3.34315 8.84315 2 10.5 2H13.5ZM14.5 5V6H9.5V5C9.5 4.44772 9.94771 4 10.5 4H13.5C14.0523 4 14.5 4.44772 14.5 5ZM6.5 7.75C7.05228 7.75 7.5 8.19772 7.5 8.75V18.75C7.5 19.3023 7.05228 19.75 6.5 19.75C5.94772 19.75 5.5 19.3023 5.5 18.75V8.75C5.5 8.19772 5.94772 7.75 6.5 7.75ZM17.5 7.75C18.0523 7.75 18.5 8.19772 18.5 8.75V18.75C18.5 19.3023 18.0523 19.75 17.5 19.75C16.9477 19.75 16.5 19.3023 16.5 18.75V8.75C16.5 8.19772 16.9477 7.75 17.5 7.75Z" />
    </Icon>
  );
}
