// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function TableIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M2 6C2 4.34315 3.34315 3 5 3H19C20.6569 3 22 4.34315 22 6V18C22 19.6569 20.6569 21 19 21H5C3.34315 21 2 19.6569 2 18V6ZM8 4.5C8.55228 4.5 9 4.94772 9 5.5V8H19.5C20.0523 8 20.5 8.44772 20.5 9C20.5 9.55228 20.0523 10 19.5 10H9V18.5C9 19.0523 8.55228 19.5 8 19.5C7.44772 19.5 7 19.0523 7 18.5V10H4.5C3.94772 10 3.5 9.55228 3.5 9C3.5 8.44772 3.94771 8 4.5 8H7V5.5C7 4.94772 7.44772 4.5 8 4.5Z" />
    </Icon>
  );
}
