// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function TagIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M11.1215 2.46447C12.0592 1.52678 13.331 1 14.657 1H21.0002C22.1048 1 23.0002 1.89543 23.0002 3V9.34315C23.0002 10.6692 22.4734 11.941 21.5357 12.8787L12.6215 21.7929C11.4499 22.9645 9.55044 22.9645 8.37887 21.7929L2.20729 15.6213C1.03572 14.4497 1.03572 12.5503 2.20729 11.3787L11.1215 2.46447ZM18.0002 7.5C18.0002 8.32843 17.3286 9 16.5002 9C15.6718 9 15.0002 8.32843 15.0002 7.5C15.0002 6.67157 15.6718 6 16.5002 6C17.3286 6 18.0002 6.67157 18.0002 7.5Z" />
    </Icon>
  );
}
