// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function TextIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M3 4C3 3.44772 3.44772 3 4 3H20C20.5523 3 21 3.44772 21 4C21 4.55228 20.5523 5 20 5H13V20C13 20.5523 12.5523 21 12 21C11.4477 21 11 20.5523 11 20V5H4C3.44772 5 3 4.55228 3 4Z" />
    </Icon>
  );
}
