// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function ThermometerIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M8 5C8 2.79086 9.79086 1 12 1C14.2091 1 16 2.79086 16 5V10.2548C17.8118 11.5186 19 13.62 19 16C19 19.866 15.866 23 12 23C8.13401 23 5 19.866 5 16C5 13.62 6.18818 11.5186 8 10.2548V5ZM11 8C11 7.44772 11.4477 7 12 7C12.5523 7 13 7.44772 13 8V13.1707C14.1652 13.5825 15 14.6938 15 16C15 17.6569 13.6569 19 12 19C10.3431 19 9 17.6569 9 16C9 14.6938 9.83481 13.5825 11 13.1707V8Z" />
    </Icon>
  );
}
