// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function ThumbsDownIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M7 13V11.0007C7 11.0004 7 11.0002 7 11V10L7 9.99809L7 5C7 3.89543 6.10457 3 5 3H4C2.89543 3 2 3.89543 2 5V13C2 14.1046 2.89543 15 4 15H5C6.10457 15 7 14.1046 7 13ZM9 5.10102L9 14.0146C9.43526 14.7538 9.84053 15.5569 10.2073 16.3649C11.0099 18.1328 11.5841 19.8232 11.8591 20.6889C12.104 21.4597 12.819 22 13.645 22C14.6695 22 15.5 21.1695 15.5 20.145V16H20.2027C21.7624 16 22.9414 14.5874 22.6624 13.0528L21.4317 6.28446C21.0859 4.3825 19.4294 3 17.4963 3H14C12.0413 3 10.2705 3.80447 9 5.10102Z" />
    </Icon>
  );
}
