// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function ThumbsUpIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M11.8591 3.31107C12.104 2.54026 12.819 2 13.645 2C14.6695 2 15.5 2.83053 15.5 3.85504V8H20.2027C21.7624 8 22.9414 9.41262 22.6624 10.9472L21.4318 17.7155C21.0859 19.6175 19.4294 21 17.4963 21H14C12.0413 21 10.2705 20.1955 9 18.899L9 9.98536C9.43526 9.24624 9.84053 8.4431 10.2073 7.63514C11.0099 5.86723 11.5841 4.17683 11.8591 3.31107ZM7 11C7 9.89543 6.10457 9 5 9H4C2.89543 9 2 9.89543 2 11V19C2 20.1046 2.89543 21 4 21H5C6.10457 21 7 20.1046 7 19L7 14.0019C7 14.0013 7 14.0006 7 14V13V12.9993V11Z" />
    </Icon>
  );
}
