// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function ToggleRightIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M1 12C1 7.58172 4.58172 4 9 4H15C19.4183 4 23 7.58172 23 12C23 16.4183 19.4183 20 15 20H9C4.58172 20 1 16.4183 1 12ZM10.5 12C10.5 9.51472 12.5147 7.5 15 7.5C17.4853 7.5 19.5 9.51472 19.5 12C19.5 14.4853 17.4853 16.5 15 16.5C12.5147 16.5 10.5 14.4853 10.5 12Z" />
    </Icon>
  );
}
