// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function TreeEvergreenIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M10.39 2.49915C11.1893 1.41435 12.8109 1.41435 13.6102 2.49915L18.6312 9.31337C19.6042 10.6339 18.6614 12.4998 17.0211 12.4998H16.1969L19.1421 15.629C20.3433 16.9054 19.4384 18.9998 17.6857 18.9998H13V21.9998C13 22.552 12.5523 22.9998 12 22.9998C11.4477 22.9998 11 22.552 11 21.9998V18.9998H6.31451C4.56177 18.9998 3.65685 16.9054 4.85812 15.629L7.80331 12.4998H6.97908C5.33879 12.4998 4.39595 10.6339 5.36897 9.31337L10.39 2.49915Z" />
    </Icon>
  );
}
