// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function TrendingDownIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M15 17C14.4477 17 14 17.4477 14 18C14 18.5523 14.4477 19 15 19H22C22.5523 19 23 18.5523 23 18V11C23 10.4477 22.5523 10 22 10C21.4477 10 21 10.4477 21 11V15.5858L13.7071 8.29289C13.3166 7.90237 12.6834 7.90237 12.2929 8.29289L9 11.5858L2.70711 5.29289C2.31658 4.90237 1.68342 4.90237 1.29289 5.29289C0.902369 5.68342 0.902369 6.31658 1.29289 6.70711L8.29289 13.7071C8.68342 14.0976 9.31658 14.0976 9.70711 13.7071L13 10.4142L19.5858 17H15Z" />
    </Icon>
  );
}
