// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function TriangleIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M14.5187 4.05189C13.3366 2.2249 10.6635 2.22489 9.48132 4.05189L2.15761 15.3704C0.866022 17.3664 2.29881 20.0001 4.67632 20.0001H19.3237C21.7013 20.0001 23.134 17.3664 21.8425 15.3704L14.5187 4.05189Z" />
    </Icon>
  );
}
