// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function TrophyIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M6 3C6 2.44772 6.44772 2 7 2H17C17.5523 2 18 2.44772 18 3V4H21C22.1046 4 23 4.89543 23 6V7C23 9.20914 21.2091 11 19 11H18C18 13.9742 15.836 16.4429 12.9967 16.9176C12.9989 16.9448 13 16.9723 13 17V20H15C15.5523 20 16 20.4477 16 21C16 21.5523 15.5523 22 15 22H9C8.44772 22 8 21.5523 8 21C8 20.4477 8.44772 20 9 20H11V17C11 16.9723 11.0011 16.9448 11.0033 16.9176C8.16399 16.4429 6 13.9742 6 11H5C2.79086 11 1 9.20914 1 7V6C1 4.89543 1.89543 4 3 4H6V3ZM18 9V6H21V7C21 8.10457 20.1046 9 19 9H18ZM6 6H3V7C3 8.10457 3.89543 9 5 9H6V6Z" />
    </Icon>
  );
}
