// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function UnderlineIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M7 3.5C7 2.94772 6.55228 2.5 6 2.5C5.44772 2.5 5 2.94772 5 3.5V10.5C5 14.366 8.13401 17.5 12 17.5C15.866 17.5 19 14.366 19 10.5V3.5C19 2.94772 18.5523 2.5 18 2.5C17.4477 2.5 17 2.94772 17 3.5V10.5C17 13.2614 14.7614 15.5 12 15.5C9.23858 15.5 7 13.2614 7 10.5V3.5ZM6 19.5C5.44772 19.5 5 19.9477 5 20.5C5 21.0523 5.44772 21.5 6 21.5H18C18.5523 21.5 19 21.0523 19 20.5C19 19.9477 18.5523 19.5 18 19.5H6Z" />
    </Icon>
  );
}
