// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function VideoIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M5 4C2.79086 4 1 5.79086 1 8V16C1 18.2091 2.79086 20 5 20H13C15.2091 20 17 18.2091 17 16V14.2732L19.6486 16.7011C20.9314 17.877 23 16.967 23 15.2268V8.77324C23 7.03302 20.9313 6.12303 19.6486 7.29893L17 9.72677V8C17 5.79086 15.2091 4 13 4H5Z" />
    </Icon>
  );
}
