// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function Volume0Icon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M14 6.13517C14 4.4395 12.0223 3.51318 10.7196 4.59873L6.72719 7.92576L4.58835 7.498C2.73197 7.12672 1 8.5466 1 10.4397V13.7902C1 15.565 2.53245 16.9519 4.29851 16.7753L6.71175 16.5339L10.8 19.6001C12.1185 20.589 14 19.6482 14 18.0001V6.13517Z" />
    </Icon>
  );
}
