// This file is auto-generated by the generate-icons script.
// Do not edit this file directly.

import type React from "react";
import { Icon } from "./_icon-primitive";

export function WarningTriangleIcon(props: React.ComponentPropsWithRef<"svg">) {
  return (
    <Icon {...props}>
      <path d="M14.598 3.5C13.4433 1.5 10.5565 1.5 9.4018 3.5L1.60757 17C0.452871 19 1.89625 21.5 4.20565 21.5H19.7941C22.1035 21.5 23.5469 19 22.3922 17L14.598 3.5ZM10.9999 12C10.9999 12.5523 11.4476 13 11.9999 13C12.5522 13 12.9999 12.5523 12.9999 12V9C12.9999 8.44772 12.5522 8 11.9999 8C11.4476 8 10.9999 8.44772 10.9999 9V12ZM11.9999 17.5C12.8283 17.5 13.4999 16.8284 13.4999 16C13.4999 15.1716 12.8283 14.5 11.9999 14.5C11.1715 14.5 10.4999 15.1716 10.4999 16C10.4999 16.8284 11.1715 17.5 11.9999 17.5Z" />
    </Icon>
  );
}
